package Login;

import ManejoDeArchivos.ManejoDeArchivos;
import Menu.Menu;
import java.io.BufferedReader; 
import java.io.FileReader;
import java.io.IOException;   
import java.io.InputStream;    
import java.io.InputStreamReader; 
import java.util.ArrayList;   
import java.util.List; 
import java.nio.charset.StandardCharsets;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    private final ManejoDeArchivos manejadorUsuarios;
    
    private List<User> users;

    public Login() {
        this.manejadorUsuarios = new ManejoDeArchivos("usuarios.txt"); 
        initComponents();
        this.setLocationRelativeTo(null);
        tfPassword.setEchoChar('•');
        cargarUsuariosDesdeArchivo();   
    }


    private void cargarUsuariosDesdeArchivo() {
        this.users = new ArrayList<>(); 
        try {
            List<String> lineas = manejadorUsuarios.leerTodasLasLineas(); 
            for (String linea : lineas) {
                String[] parts = linea.split(","); 
                if (parts.length >= 3) {
                    try {
                        int accessLevel = Integer.parseInt(parts[0].trim());
                        String username = parts[1].trim();
                        String password = parts[2].trim();
                        this.users.add(new User(username, password, accessLevel));
                    } catch (NumberFormatException e) {
                        System.err.println("Error de formato numérico en la línea: " + linea);
                    }
                }
            }
          //  JOptionPane.showMessageDialog(this, "Se cargaron " + this.users.size() + " usuarios.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error fatal al leer el archivo de usuarios: " + e.getMessage(), "Error de Archivo", JOptionPane.ERROR_MESSAGE); //
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JLabel();
        txtsingin = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        tglMostrarClave = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(PaletaDeColores.FONDO_GRIS_SUAVE);

        jPanel1.setBackground(PaletaDeColores.FONDO_GRIS_SUAVE);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(PaletaDeColores.FONDO_GRIS_SUAVE);
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtUsuario.setText("Usuario");
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 143, -1, -1));

        txtsingin.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        txtsingin.setText("Login");
        jPanel1.add(txtsingin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtPassword.setText("Contraseña");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        btnLogin.setBackground(PaletaDeColores.AZUL_CORPORATIVO);
        btnLogin.setText("Iniciar Sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));
        jPanel1.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, -1));

        tglMostrarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-eye-checked-24.png"))); // NOI18N
        tglMostrarClave.setBorder(null);
        tglMostrarClave.setContentAreaFilled(false);
        tglMostrarClave.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglMostrarClaveItemStateChanged(evt);
            }
        });
        tglMostrarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglMostrarClaveActionPerformed(evt);
            }
        });
        jPanel1.add(tglMostrarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-user-30.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-password-30.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String enteredUsername = tfUsuario.getText().trim();
        String enteredPassword = new String(tfPassword.getPassword()).trim();

        if (enteredUsername.isEmpty() || enteredPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese usuario y contraseña.", "Campos Obligatorios", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User authenticatedUser = null;
        for (User user : users) {
            if (user.username.equals(enteredUsername) && user.password.equals(enteredPassword)) {
                authenticatedUser = user;
                break;
            }
        }

   if (authenticatedUser != null) {
    String nombreCompleto = authenticatedUser.username;
    int nivelDeAcceso = authenticatedUser.accessLevel;

    try {
        List<String> lineas = manejadorUsuarios.leerTodasLasLineas();
        for (String linea : lineas) {
            String[] parts = linea.split(",");
            if (parts.length > 4 && parts[1].trim().equals(authenticatedUser.username)) {
                nombreCompleto = parts[3].trim() + " " + parts[4].trim();
                break;
            }
        }
    } catch (Exception e) {
        System.err.println("Error al leer archivo para obtener nombre completo: " + e.getMessage());
    }

    JOptionPane.showMessageDialog(this, "¡Bienvenido, " + nombreCompleto + "!", "Inicio de Sesión Exitoso", JOptionPane.INFORMATION_MESSAGE);

    Menu menuPrincipal = new Menu(nombreCompleto, nivelDeAcceso);
    menuPrincipal.setVisible(true);
    
    this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de Inicio de Sesión", JOptionPane.ERROR_MESSAGE);
            tfPassword.setText("");
            tfUsuario.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tglMostrarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglMostrarClaveActionPerformed

    }//GEN-LAST:event_tglMostrarClaveActionPerformed

    private void tglMostrarClaveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglMostrarClaveItemStateChanged
    
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
       
        tfPassword.setEchoChar((char) 0);
    } else {
       
        tfPassword.setEchoChar('•');
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tglMostrarClaveItemStateChanged

    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsuario;
    private javax.swing.JToggleButton tglMostrarClave;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUsuario;
    private javax.swing.JLabel txtsingin;
    // End of variables declaration//GEN-END:variables
}
